### ISSUE TITLE
Installed on Windows7 Doesn't work.

### ISSUE THREAD

**Issue by lacostenycoder** [jaunkst/atom-html2haml#15] opened 2015-08-17 16:40 UTC
``` html
<p>
<h4>18.0 Megapixel CMOS Sensor and Dual DIGIC 4 Image Processors for high image quality and speed</h4>
</p>
<p>
The EOS 7D features a Canon-designed 18.0 Megapixel APS-C size CMOS sensor that captures such a high level of resolution it’s easy to crop images for enlargement without concern of losing detail. A major factor in reducing noise, the CMOS sensor assures that images shot at highest sensitivity will be remarkably smooth. Dual DIGIC 4 Image Processors ensure that images are captured, processed and saved with remarkable speed. The EOS 7D’s ability to capture and process data of images shot at 18.0 Megapixels at 8.0 fps, as well as Face Detection Live Mode, Full HD video recording, Auto Lighting Optimizer and Lens Peripheral optimization are all possible thanks to the Dual DIGIC 4 Image Processors.
</p>
<center>
  <div class="padding20t padding20b">
    <img class="img-responsive" src="http://www.usa.canon.com/CUSA/assets/app/images/EOS_2009/7D/features/7d_feature_01a.jpg" max-width="100%">
  </div>
</center>
```

Any ideas?

![shot](https://cloud.githubusercontent.com/assets/6077905/9310277/d879e542-44dc-11e5-8dff-332efcefd518.jpg)

**Comment by jibiel** [comment] 2015-09-22 20:58
Seems like duplicate of #14.

**Closed** 2017-06-06 04:59 UTC
Labels: duplicate
